version: '3.8'

services:
  fastapi_test:
    image: 125044483968.dkr.ecr.us-east-1.amazonaws.com/lexy/deudor/fastapi:latest
    container_name: fastapi_test
    ports:
      - "8000:8000"
    env_file: .env
    command:
      - uvicorn
      - fastapi_test:app
      - --host
      - 0.0.0.0
      - --port
      - "8000"
    networks:
      - lexy_net

networks:
  lexy_net:
    driver: bridge
